### ISSUE TITLE
Bug - Flashcard not deleted once past level threshold

### ISSUE THREAD

**Issue by itsNatTan** [AY2324S1-CS2103T-T11-4/tp#168]
This causes the flashcard to still be stored for the next session, in which it will cause the data to not be loaded as it is considered erronous data.

Fix - Delete flashcard from JSON and ObservableList once it is past the level threshold

**Comment by itsNatTan** [comment]
![image](https://github.com/AY2324S1-CS2103T-T11-4/tp/assets/64185574/4f3bbf13-e935-413b-bfb8-54ad7ed30ee5)
![image](https://github.com/AY2324S1-CS2103T-T11-4/tp/assets/64185574/ecc4b64a-50da-48d1-a356-91750d3ea1cb)
![image](https://github.com/AY2324S1-CS2103T-T11-4/tp/assets/64185574/10d3c5a8-c82d-4547-b7a3-b2889dcc4930)

**Comment by A1WAYSD** [comment]
I've changed deleteThreshold to only take effect when filtering words for review session. Flashcards having levels beyond threshold can still save in storage and be displayed with the list command.
